import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,current,examine,question,decide,advance,nextWatch,finish,unlockSignal,loadGame,saveGame} from '../src/game.js';
import {PEOPLE,ENDINGS} from '../src/content.js';

function play(seed,policy,setup=()=>{}){const s=createGame(seed);setup(s);while(s.phase!=='ending'){if(s.phase==='arrival'){assert.equal(decide(s,policy(current(s),s)),true);}else if(s.phase==='aftermath')advance(s);else if(s.phase==='interval')nextWatch(s);else throw Error('Stalled state');}return s;}
test('a seed gives reproducible complete encounters',()=>{assert.deepEqual(createGame(1704),createGame(1704));assert.notDeepEqual(createGame(1704).encounters,createGame(1705).encounters);});
test('every generated cast is adult, unique, and has four to six visitors',()=>{for(let seed=0;seed<200;seed++){const s=createGame(seed),n=s.encounters.filter(e=>e.visitor).length;assert.equal(new Set(s.encounters.map(e=>e.personId)).size,12);assert.ok(n>=4&&n<=6);for(const e of s.encounters){assert.ok(PEOPLE.find(p=>p.id===e.personId).age>=21);if(e.visitor)assert.ok(e.signs.some(Boolean));}}});
test('all characters can be human or visitors across runs',()=>{for(const p of PEOPLE){const possibilities=new Set(Array.from({length:80},(_,i)=>createGame(i).encounters.find(e=>e.personId===p.id).visitor));assert.equal(possibilities.size,2);}});
test('examination consumes time once and does not reveal hidden identity',()=>{const s=createGame(17),r=examine(s,'thermal');assert.equal(s.time,83);assert.equal(examine(s,'thermal'),null);assert.equal(s.time,83);assert.equal('visitor' in r,false);});
test('questions consume time once and survive serialization',()=>{const s=createGame(1);assert.equal(typeof question(s,'alibi'),'string');assert.equal(s.time,85);assert.equal(question(s,'alibi'),null);const restored=JSON.parse(JSON.stringify(s));assert.equal(question(restored,'alibi'),null);});
test('invalid examinations and questions have no effects',()=>{const s=createGame(0),before=JSON.stringify(s);assert.equal(examine(s,'bogus'),null);assert.equal(question(s,'bogus'),null);assert.equal(JSON.stringify(s),before);});
test('decisions are irreversible and consume ammunition only for shots',()=>{const s=createGame(2);assert.ok(decide(s,'shoot'));assert.equal(s.ammo,5);assert.equal(s.noise,24);assert.equal(decide(s,'admit'),false);assert.equal(s.decisions.length,1);assert.equal(examine(s,'thermal'),null);});
test('empty weapon cannot shoot but player can still reject',()=>{const s=createGame(2);s.ammo=0;assert.equal(decide(s,'shoot'),false);assert.equal(s.phase,'arrival');assert.equal(decide(s,'reject'),true);});
test('four decisions move to the next watch and award two rounds',()=>{const s=createGame(3);for(let i=0;i<4;i++){decide(s,'reject');advance(s);}assert.equal(s.night,2);assert.equal(s.phase,'interval');assert.equal(s.ammo,8);nextWatch(s);assert.equal(s.phase,'arrival');assert.equal(s.index,4);});
test('all-safe play saves humans and reaches the dawn ending',()=>{const s=play(17,p=>p.visitor?'reject':'admit');assert.equal(s.ending,'dawn');assert.equal(s.index,12);assert.equal(s.health,100);});
test('rejecting everyone reaches the lonely ending',()=>assert.equal(play(19,()=> 'reject').ending,'alone'));
test('admitted visitors drain resolve at watch boundaries',()=>{const s=createGame(12);for(let i=0;i<4;i++){s.encounters[i].visitor=i===0;decide(s,'admit');advance(s);}assert.equal(s.health,81);});
test('excess noise inflicts damage even if every shot killed a visitor',()=>{const s=createGame(12);for(let i=0;i<4;i++){s.encounters[i].visitor=true;decide(s,'shoot');advance(s);}assert.ok(s.health<100);});
test('three innocent kills lead to the blood ending when alive',()=>{const s=createGame(12);s.decisions=PEOPLE.slice(0,3).map(p=>({id:p.id,action:'shoot',visitor:false}));finish(s);assert.equal(s.ending,'blood');});
test('two infiltrators lead to a breach',()=>{const s=createGame(12);s.decisions=PEOPLE.slice(0,2).map(p=>({id:p.id,action:'admit',visitor:true}));finish(s);assert.equal(s.ending,'breach');});
test('relay requires both discovered clues and correct code',()=>{const s=createGame(0);assert.equal(unlockSignal(s,'1704').ok,false);s.notes=['incident'];assert.equal(unlockSignal(s,'1704').ok,false);s.notes.push('photograph');assert.equal(unlockSignal(s,'0417').ok,false);assert.equal(s.noise,8);assert.equal(unlockSignal(s,'1704').ok,true);assert.equal(s.signalOff,true);finish(s);assert.equal(s.ending,'signal');});
test('relay shutdown prevents damage from visitors',()=>{const s=play(0,()=> 'admit',s=>{s.notes=['incident','photograph'];unlockSignal(s,'1704');});assert.equal(s.health,100);assert.equal(s.ending,'signal');});
test('hundreds of mixed runs always end without negative ammunition',()=>{for(let seed=0;seed<200;seed++){const s=play(seed,(_,s)=>s.ammo>0&&s.index%3===0?'shoot':s.index%2===0?'admit':'reject');assert.ok(ENDINGS[s.ending]);assert.ok(s.ammo>=0);assert.ok(s.health>=0);assert.ok(s.trust>=0&&s.trust<=100);assert.ok(s.index<=12);}});
test('fatal watch damage produces the fallen ending',()=>{const s=createGame(0);s.health=1;s.phase='aftermath';s.index=3;s.noise=90;advance(s);assert.equal(s.ending,'fallen');});
test('save and resume retain the exact encounter state',()=>{let raw;globalThis.localStorage={setItem:(_,v)=>raw=v,getItem:()=>raw};const s=createGame(4);examine(s,'uv');question(s,'alibi');saveGame(s);assert.deepEqual(loadGame(),s);raw='{broken';assert.equal(loadGame(),null);raw=JSON.stringify({...s,phase:'ending'});assert.equal(loadGame(),null);delete globalThis.localStorage;});
