import test from 'node:test';
import assert from 'node:assert/strict';
import {Haunting,playerName} from '../src/haunting.js';
import {createGame,saveGame,loadGame} from '../src/game.js';
import {Intercom} from '../src/voice.js';
import {inWalkableArea} from '../src/navigation.js';
import {Sound} from '../src/audio.js';

const active={active:true,enabled:true,signalOff:false,ready:true,name:'Aisha'};
test('nicknames preserve Unicode and punctuation, with bounded length and neutral fallback',()=>{assert.equal(playerName('  Mei   Lin  '),'Mei Lin');assert.equal(playerName('陈小明'),'陈小明');assert.equal(playerName("D’Souza"),"D’Souza");assert.equal(playerName('<>\n\u202e'),'Resident');assert.equal(playerName('a'.repeat(50)).length,28);assert.ok(!playerName('<script>').includes('<'));});
test('the chosen name survives save/resume without changing randomized identities',()=>{const named=createGame(17,'Ravi');assert.deepEqual(named.encounters,createGame(17).encounters);let raw;globalThis.localStorage={setItem:(_,s)=>raw=s,getItem:()=>raw};saveGame(named);assert.equal(loadGame().playerName,'Ravi');const old=JSON.parse(raw);delete old.playerName;raw=JSON.stringify(old);assert.equal(loadGame().index,0);delete globalThis.localStorage;});
test('personalized calls respect pauses, disabled setting and a disconnected relay',()=>{for(const flags of [{active:false},{enabled:false},{signalOff:true}]){const h=new Haunting(()=>0);assert.equal(h.tick(1000,{...active,...flags}),null);assert.equal(h.remaining,28);} });
test('calls wait for a quiet moment and never emit a backlog',()=>{const h=new Haunting(()=>0);assert.equal(h.tick(28,{...active,ready:false}),null);assert.match(h.tick(1,active),/Aisha/);assert.equal(h.tick(1,active),null);assert.equal(h.remaining,74);});
test('calls do not repeat consecutively and are capped at six per play session',()=>{const h=new Haunting(()=>0);let previous='';for(let i=0;i<6;i++){const line=h.tick(200,active);assert.ok(line);assert.notEqual(line,previous);previous=line;}assert.equal(h.tick(999,active),null);h.reset();assert.ok(h.tick(200,active));});
function mockedIntercom(){let options;const messages=[],changes=[],transcripts=[];const session={setVolume(){},sendContextualUpdate(){},setMicMuted(){},sendUserMessage:v=>messages.push(v),endSession:async()=>{}};const i=new Intercom(s=>changes.push(s),(who,text)=>transcripts.push({who,text}),async()=>({Conversation:{startSession:async opts=>{options=opts;return session;}}}));return {i,messages,changes,transcripts,options:()=>options};}
test('ElevenLabs receives player_name and game_context before its first response',async()=>{const m=mockedIntercom();await m.i.connect('agent_test','Observed evidence only','Ravi');assert.deepEqual(m.options().dynamicVariables,{game_context:'Observed evidence only',player_name:'Ravi'});await m.i.disconnect();});
test('live name cues wait for silence and suppress calls while muted or speaking',async()=>{const m=mockedIntercom();await m.i.connect('agent_test','context','Mei');assert.equal(m.i.whisper('Mei…'),false);m.i.lastActivity=0;assert.equal(m.i.whisper('Mei…'),true);assert.equal(m.messages.length,1);assert.equal(m.i.whisper('Mei…'),false);m.i.lastActivity=0;m.i.pendingUntil=0;m.i.mute();assert.equal(m.i.canWhisper,false);m.i.mute();m.options().onModeChange({mode:'speaking'});assert.equal(m.i.canWhisper,false);await m.i.disconnect();assert.equal(m.i.canWhisper,false);});
test('stale voice callbacks after disconnect do not revive the connection',async()=>{const m=mockedIntercom();await m.i.connect('agent_test','context','Mark');const options=m.options();await m.i.disconnect();options.onModeChange({mode:'speaking'});options.onMessage({source:'ai',message:'late response'});assert.equal(m.changes.at(-1),'Disconnected');assert.equal(m.transcripts.length,0);});
test('browser audio resumes a suspended context on an explicit interaction',async()=>{const s=new Sound();let resumed=0;s.ctx={resume:async()=>{resumed++;}};await s.start();assert.equal(resumed,1);});
