import './admin.css';
import {upload} from '@vercel/blob/client';
import {loadMemories,saveLocalMetadata,MEMORY_PLACEMENTS,placedMemory,addLocalMemory} from './memories.js';
import {cleanMemoryMetadata,formatMemoryDate} from './memory-metadata.js';
const root=document.querySelector('#studio'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],selected=null,session={},busy=false,message='';
async function api(path='',body){const r=await fetch('/api/memories'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),credentials:'same-origin'});let data;try{data=await r.json();}catch{throw Error('Cloud storage is available on the Vercel deployment. Local editing still works here.');}if(!r.ok)throw Error(data.error||'Unable to connect');return data;}
async function refresh(){for(const m of items)if(m.src?.startsWith('blob:'))URL.revokeObjectURL(m.src);items=await loadMemories({cloud:false});try{session=await api('?action=session');if(session.authenticated)items.push(...await api('?admin=1'));}catch{session={};}render();}
const locations=()=>MEMORY_PLACEMENTS.map(p=>`<option value="${p.id}">${esc(p.title)} · ${esc(p.room)}</option>`).join('');
function render(){const m=items.find(m=>m.id===selected);root.innerHTML=`<header><a href="/">At Home.</a><span>Memory studio</span>${session.authenticated?'<button data-action="logout">Sign out</button>':''}</header><main><section class="intro"><p class="eyebrow">Keep the moments that matter</p><h1>A house full of memories.</h1><p>Add a date, tell the story, and choose where each moment belongs.</p></section><p role="status" id="status">${esc(message)}</p>
 ${!session.authenticated?`<section class="connection"><div><h2>Cloud memories</h2><p>${session.configured?'Sign in to upload and edit memories across devices.':session.storage?'Your private store is connected. Set MEMORY_ADMIN_PASSWORD in the At Home Vercel project to enable the editor.':'Local editing is available now. Open this editor on the Vercel deployment for cloud storage.'}</p></div><form id="login"><label>Editor password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in</button></form></section>`:'<p class="connection-note">Private storage connected · New uploads start as drafts. Published memories are visible to anyone who can open the game.</p>'}
 <div class="workspace"><aside><button class="primary" data-action="new">+ Add a memory</button><div class="library">${items.map(i=>`<button data-id="${esc(i.id)}" class="${i.id===selected?'selected':''}"><strong>${esc(i.title)}</strong><small>${i.cloud?(i.published?'Published':'Private draft'):'This device'}${i.date?' · '+esc(formatMemoryDate(i.date)):''}</small></button>`).join('')||'<p>Your first memory starts here.</p>'}</div></aside><section class="editor">${selected==='new'?`<h2>A new memory</h2><form id="new-memory"><label>Photo or video<input name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" required></label><label>Title<input name="title" maxlength="100" required></label><label>Date <small>Optional</small><input name="date" type="date"></label><label>Description<textarea name="description" rows="3" maxlength="1600"></textarea></label><label>Memory spot<select name="placement">${locations()}</select></label><p class="fine">JPG, PNG, WebP, MP4, WebM or MOV · Up to 250 MB. MP4 gives the widest video playback support.</p><button class="primary">${session.authenticated?'Upload as private draft':'Save on this device'}</button><progress id="progress" max="100" value="0" hidden></progress></form>`:m?`<div class="preview">${m.type==='video'?`<video controls playsinline preload="metadata" src="${esc(m.src)}"></video>`:`<img src="${esc(m.src)}" alt="${esc(m.title)}">`}</div><form id="edit-memory"><label>Title<input name="title" value="${esc(m.title)}" maxlength="100" required></label><div class="row"><label>Date <small>Optional</small><input name="date" type="date" value="${esc(m.date)}"></label><label>Memory spot<select name="placement"><option value="keep">Keep current location</option>${locations()}</select></label></div><label>Description<textarea name="description" rows="4" maxlength="1600">${esc(m.description)}</textarea></label>${m.cloud?`<label class="check"><input type="checkbox" name="published" ${m.published?'checked':''}><span>Show this memory in the game<br><small>Anyone who opens the game can relive it.</small></span></label>`:''}<div class="row"><button class="primary">Save changes</button>${!m.cloud&&session.authenticated?'<button type="button" data-action="upload-local">Copy to cloud as private draft</button>':''}</div><progress id="progress" max="100" value="0" hidden></progress></form>`:'<div class="empty"><span>✧</span><h2>Make a moment your own.</h2><p>Select a memory to edit its story, or add a new one.</p></div>'}</section></div></main>`;}
function status(text){message=text;const el=document.querySelector('#status');if(el)el.textContent=text;}
function lock(value){busy=value;for(const el of root.querySelectorAll('button,input,textarea,select'))el.disabled=value;}
const metadata=form=>cleanMemoryMetadata(Object.fromEntries(new FormData(form)));
function location(form,m){const id=new FormData(form).get('placement');return id==='keep'?m.position:placedMemory(MEMORY_PLACEMENTS.find(p=>p.id===id)||MEMORY_PLACEMENTS[0]).position;}
async function cloudUpload(file,meta,position){
 const extensions={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'},ext=extensions[file.type];if(!ext||file.size>250*1024*1024)throw Error('Choose a supported photo or video smaller than 250 MB.');
 const id=crypto.randomUUID(),mediaPath=`media/${id}/${file.type.startsWith('video/')?'video':'image'}.${ext}`;
 status('Uploading securely…');const progress=document.querySelector('#progress');if(progress)progress.hidden=false;
 await upload(mediaPath,file,{access:'private',handleUploadUrl:'/api/memory-upload',multipart:true,contentType:file.type,onUploadProgress:({percentage})=>{if(progress)progress.value=percentage;}});
 const saved=await api('',{id,...meta,position,mediaPath,published:false});selected=saved.id;status('Saved to the cloud as a private draft.');
}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{
 if(b.dataset.id){selected=b.dataset.id;message='';render();return;}
 if(b.dataset.action==='new'){selected='new';message='';render();return;}
 if(b.dataset.action==='logout'){lock(true);await api('?action=logout',{});selected=null;await refresh();}
 if(b.dataset.action==='upload-local'){const m=items.find(m=>m.id===selected),form=document.querySelector('#edit-memory'),meta=metadata(form),position=location(form,m);lock(true);const r=await fetch(m.src);if(!r.ok)throw Error('Could not read the original file');await cloudUpload(m.file||await r.blob(),meta,position);await refresh();}
 }catch(error){status(error.message);}finally{lock(false);}});
root.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const form=e.target;try{
 // Read fields before disabling them: disabled controls are excluded from FormData.
 const fields=new FormData(form);
 if(form.id==='login'){lock(true);await api('?action=login',{password:fields.get('password')});status('Signed in.');await refresh();return;}
 const meta=metadata(form),m=items.find(m=>m.id===selected),position=location(form,m);lock(true);
 if(form.id==='new-memory'){const file=fields.get('file');if(session.authenticated)await cloudUpload(file,meta,position);else{const added=await addLocalMemory(file,{position,description:meta.description},meta.title);await saveLocalMetadata(added.id,{...meta,position});URL.revokeObjectURL(added.src);selected=added.id;status('Saved on this device.');}}
 else if(m.cloud){await api('',{...m,...meta,position,published:fields.has('published')});status('Changes saved to the cloud.');}
 else{await saveLocalMetadata(m.id,{...meta,position});status('Changes saved on this device.');}
 await refresh();
 }catch(error){status(error.message);}finally{lock(false);}});
refresh();
