export const PEOPLE = [
  { id:'tan', name:'Daniel Tan', role:'Mathematics lecturer', age:46, color:0xb2b2a0, skin:0xb98061, hair:0x20201b, glasses:true, opening:'You know me. Room 04-07, every Tuesday. Please open the door.', alibi:'I was marking scripts in the staff room. The first siren cut the power.', memory:'The canteen uncle always keeps my kopi o kosong behind the counter.', record:'D. Tan — staff room, Block B. Atrial arrhythmia noted on first-aid record.', humanClue:'My heart skips sometimes. It is in the first-aid file.' },
  { id:'aisha', name:'Aisha Rahman', role:'Design student · year 2', age:22, color:0x436e60, skin:0x9e6b4f, hair:0x1c2423, opening:'There is someone on the stairs wearing my face. Don’t make me go back.', alibi:'I was in the print studio. My access card is still on the scanner.', memory:'The lift has been stuck on level three since last semester.', record:'A. Rahman — print studio booking, 20:00–23:30. Recovering from a fever.', humanClue:'I took paracetamol an hour ago. My temperature is all over the place.' },
  { id:'lim', name:'Marcus Lim', role:'Engineering student · year 3', age:24, color:0x747d8c, skin:0xc99572, hair:0x151718, opening:'I heard the announcement. You are supposed to let students shelter here.', alibi:'Workshop two. I stayed back to finish a circuit board.', memory:'We call the vending machine the donation box. It never gives change.', record:'M. Lim — workshop access valid. Solvent exposure; protective gloves required.', humanClue:'That white stuff is resin. I was sanding a prototype.' },
  { id:'kavitha', name:'Kavitha Menon', role:'Chemistry lecturer', age:39, color:0xaca38a, skin:0x7c4b36, hair:0x1b1617, glasses:true, opening:'Do not touch the water fountains. I saw what came out of one.', alibi:'Chemistry prep room. I was locking the solvent cabinet.', memory:'The principal banned durian, but the staff fridge still smells of it.', record:'K. Menon — chemistry prep room. Optical brighteners used in practical class.', humanClue:'The UV residue is from the lab. Check the practical schedule.' },
  { id:'wei', name:'Wei Jie Ong', role:'Media student · year 1', age:21, color:0xb2a17c, skin:0xc48b68, hair:0x191512, opening:'My phone died. My mother is waiting at the bus stop. Is there a charger inside?', alibi:'Editing suite. I fell asleep with my headphones on.', memory:'There is a cracked tile outside the library shaped like Singapore.', record:'W. J. Ong — editing suite login at 21:42. No medical flags.', humanClue:'I ran four flights. Of course my pulse is high.' },
  { id:'siti', name:'Siti Hassan', role:'Campus librarian', age:51, color:0x6b6570, skin:0xa57858, hair:0x2b2221, glasses:true, opening:'I have the evacuation register. There are more names on it than there were this morning.', alibi:'The library archive. I heard the shutters come down.', memory:'The old school bell rings seventeen seconds too late.', record:'S. Hassan — library closing duty. Recently treated for circulation problems.', humanClue:'My hands are always cold. Ask anyone who works with me.' },
  { id:'raj', name:'Raj Kumar', role:'Sports science student · year 2', age:23, color:0x56747c, skin:0x825039, hair:0x161416, opening:'I carried someone up from the court. They stopped breathing. Then they started talking.', alibi:'The sheltered court. We were packing up after training.', memory:'Coach makes us run the stairs when we say it is too humid.', record:'R. Kumar — court booking until 22:00. Wrist injury; sports tape issued.', humanClue:'The marks on my wrist are from the tape. I pulled it off.' },
  { id:'goh', name:'Evelyn Goh', role:'Student counsellor', age:34, color:0x95796e, skin:0xbd876b, hair:0x28221c, opening:'There are people crying behind the fire door. But all of them are crying at the same time.', alibi:'Counselling room. My last appointment ran late.', memory:'The fish in reception is called Principal. Nobody says it in front of him.', record:'E. Goh — counselling room, Block A. Migraine medication may alter pupil response.', humanClue:'I get migraines. The torch is making it worse.' },
  { id:'ben', name:'Benjamin Teo', role:'Computing student · year 3', age:25, color:0x526459, skin:0xb8835f, hair:0x141414, glasses:true, opening:'The campus network is still up. Someone keeps adding users. They all have the same birthday.', alibi:'Server room. I was running a backup for my final project.', memory:'The Wi-Fi password used to be on a Post-it under the router.', record:'B. Teo — temporary server access. Overnight maintenance authorised.', humanClue:'I have not slept since yesterday. I know I look terrible.' },
  { id:'farah', name:'Farah Ismail', role:'Business student · year 2', age:22, color:0x857956, skin:0xa77856, hair:0x1b2020, opening:'I was with three others. I turned around and there were four. I just ran.', alibi:'Seminar room three. Our presentation is due tomorrow.', memory:'The auntie at the drinks stall calls everyone boss, even the lecturers.', record:'F. Ismail — seminar room three, group booking. Eczema noted at wrist.', humanClue:'That rash was there before tonight. It gets worse when I am stressed.' },
  { id:'chan', name:'Patrick Chan', role:'Facilities supervisor', age:57, color:0x536774, skin:0xad795a, hair:0x62625b, opening:'I locked the main gate myself. Whatever is out there did not come through the gate.', alibi:'Electrical switch room. The circuit breakers keep tripping.', memory:'The fourth-floor clock has not worked since the April flood.', record:'P. Chan — electrical duty. Left forearm scar from 2019 workplace injury.', humanClue:'That scar is seven years old. The accident report is in the office.' },
  { id:'mei', name:'Mei Lin Chen', role:'Nursing student · year 3', age:24, color:0x8faaaa, skin:0xc79578, hair:0x231b18, opening:'Let me help. I have first-aid training. I can hear someone coughing in there.', alibi:'Simulation ward. I was checking the practice mannequins.', memory:'The anatomy skeleton wears a Santa hat all year. His name is Mr Bones.', record:'M. L. Chen — simulation ward. Latex gloves may leave fluorescent powder.', humanClue:'It is glove powder. Look at the cuffs, not just my hands.' },
];

export const DOCUMENTS = {
  protocol: { title:'CIVIL DEFENCE // 22:41', tag:'Emergency broadcast', text:'Remain indoors until 06:00. Do not rely on appearance or personal memories. The visitors repeat what they hear.\n\nLow temperature, abnormal pulse, and fluorescent residue have been reported. NONE is conclusive alone. Stress, medication and laboratory work can imitate these signs.\n\nCross-check all available evidence. Every examination takes time. Every shot is heard. Unattended arrivals will leave.' },
  register: { title:'AFTER-HOURS REGISTER', tag:'Records cabinet', text:'All students enrolled in the night programme are aged 21 or older. Staff and students listed here have valid campus access. A familiar name is not proof of identity.\n\nThe personal record of the person at your door is available under their dossier.' },
  incident: { title:'INCIDENT 17 / 04', tag:'Recovered maintenance report', text:'17 April. 02:13. A voice continued over the public-address system after we unplugged the amplifier.\n\nThe basement relay was sealed. Emergency override remains the incident date: DAY, THEN MONTH. Four digits.\n\nIf the same voice returns, do not answer. Disconnect its carrier with the manual radio terminal.' },
  photograph: { title:'THE FOURTH-FLOOR PHOTOGRAPH', tag:'A photograph behind the board', text:'Twelve people stand outside this classroom. The caption says 17 APRIL. Everyone faces the camera except the figure in the window.\n\nOn the back: “They do not enter through doors. They enter when we agree that they belong.”\n\nUnderneath, in different handwriting: “The relay calls them here. Shut it down before first light.”' },
};

export const ENDINGS = {
  dawn: { title:'THE LAST BELL', subtitle:'You kept the door. You kept your humanity.', text:'At 06:00, rain gives way to birdsong. The people you sheltered walk down the stairs together. You count them twice. The number stays the same.' },
  alone: { title:'PERFECT ATTENDANCE', subtitle:'The door held. The silence stayed.', text:'The rescue team finds too many empty chairs. Outside, abandoned bags line the corridor. You can still name the people who carried them. Survival does not feel the way you expected.' },
  blood: { title:'A QUIET CLASSROOM', subtitle:'Fear made every decision for you.', text:'The rescue team asks you to put the weapon down. You try to explain the signs. The residue. The cold hands. The words sound smaller in daylight.' },
  breach: { title:'ONE OF US', subtitle:'You gave it somewhere to belong.', text:'Someone inside says your name in your own voice. The lights come on. Every face turns toward you at exactly the same time. Outside, the bell begins to ring.' },
  signal: { title:'DEAD AIR', subtitle:'You ended the invitation.', text:'The relay falls silent. Beyond the windows, every borrowed face looks up. Then the shapes loosen like smoke in the rain. For the first time all night, the school is only a school.' },
  fallen: { title:'THE OPEN DOOR', subtitle:'The corridor remembers the noise.', text:'The last shot echoes much longer than it should. Something answers from every floor. The lock was never built to hold back this many.' },
};
