import './style.css';
import {School} from './scene.js';
import {Sound} from './audio.js';
import {Intercom} from './voice.js';
import {PEOPLE,DOCUMENTS,ENDINGS} from './content.js';
import {createGame,current,examine,question,decide,advance,nextWatch,unlockSignal,saveGame,loadGame} from './game.js';

const app=document.querySelector('#app');
const sound=new Sound();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',sound:'<path d="m11 5-6 4H2v6h3l6 4V5Zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="m9 3-1 3-3 1-2 3 2 3v4l4 2 3-1 3 1 4-2v-4l2-3-2-3-3-1-1-3Z"/>',book:'<path d="M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3V4Zm9 2v15"/>',pulse:'<path d="M2 12h5l3-8 4 16 3-8h5"/>',thermal:'<path d="M9 14V5a3 3 0 0 1 6 0v9a5 5 0 1 1-6 0Z"/><path d="M12 8v10"/>',uv:'<path d="m8 3 8 0-1 8-6 0-1-8ZM10 11v10h4V11M3 13l3 1m12 0 3-1M5 7h1m12 0h1"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/>',radio:'<path d="m6 8 13-5M3 8h18v13H3z"/><circle cx="8" cy="15" r="3"/><path d="M14 12h4m-4 3h4m-4 3h4"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',target:'<circle cx="12" cy="12" r="7"/><path d="M12 1v7m0 8v7M1 12h7m8 0h7"/>',door:'<path d="M5 21V3h14v18M2 21h20M15 12h1"/>',moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',bullet:'<path d="M8 21V8c0-4 4-6 4-6s4 2 4 6v13H8Zm0-5h8"/>'};
const icon=(n)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.arrow}</svg>`;
let state=null,screen='menu',modal=null,tab='evidence',log=[],lastReply='',settings={volume:.5,blood:true,motion:true,voices:false},scene,toastTimeout;
let agentId=import.meta.env.VITE_ELEVENLABS_AGENT_ID||'',voiceState='Disconnected',transcript=[];
try{Object.assign(settings,JSON.parse(localStorage.getItem('last-bell-settings')||'{}'));}catch{}
sound.setVolume(settings.volume);sound.voices=settings.voices;
const intercom=new Intercom(s=>{voiceState=s;const el=document.querySelector('#voice-state');if(el)el.textContent=s;const live=document.querySelector('#voice-live');if(live){live.hidden=s==='Disconnected';live.textContent=`${s==='Microphone muted'?'MIC MUTED':'INTERCOM LIVE'} · DISCONNECT`;}},(who,text)=>{transcript.push({who,text});transcript=transcript.slice(-12);const el=document.querySelector('#transcript');if(el){el.innerHTML=transcript.map(t=>`<p><b>${esc(t.who)}</b>${esc(t.text)}</p>`).join('');el.scrollTop=el.scrollHeight;}});
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),4200);}
try{scene=new School(document.querySelector('#world'),interact,shoot,look);scene.blood=settings.blood;scene.motion=settings.motion;}
catch(error){console.error(error);app.innerHTML='<main class="fallback"><h1>LAST BELL</h1><p>This game needs WebGL 2. Enable graphics acceleration in your browser, then reload.</p><button onclick="location.reload()">Try again</button></main>';throw error;}
function context(){const p=state&&current(state);return `Fictional horror game LAST BELL at Singapore adult night school. Watch ${state?.night||1}/3. Person at door: ${p?.name||'nobody'}, ${p?.role||''}. Observed evidence: ${log.map(x=>x.text).join(' ')}. Sheltered: ${state?.sheltered.length||0}. Signal ${state?.signalOff?'disconnected':'active'}. You are the unsettling school intercom. You do not know who is human; never claim certainty. Keep responses short. Do not reveal puzzle codes.`;}
function sync(){if(state){state.log=log;state.lastReply=lastReply;saveGame(state);}intercom.update(context());}
function menu(){screen='menu';modal=null;scene.setMode('menu');scene.showPerson(null);sound.hush();intercom.disconnect().catch(()=>{});render();}
function start(resume=false){
  sound.start();state=resume?loadGame():createGame();if(!state)state=createGame();log=state.log||[];lastReply=state.lastReply||'';tab='evidence';screen='game';modal=null;scene.reset();scene.setMode('play');scene.showPerson(current(state));
  if(state.phase==='aftermath')scene.showPerson(null);
  sound.knock();sync();render();if(!resume)showModal('briefing');
}
function arrive(){log=[];lastReply='';tab='evidence';scene.door.rotation.y=-.16;scene.showPerson(current(state));scene.focus('door');sound.knock();sync();render();sound.speak(current(state)?.opening||'');}
function performScan(kind){if(modal||screen!=='game')return;const result=examine(state,kind);if(!result)return;log.push({...result,title:{thermal:'Thermal scan',pulse:'Pulse reading',uv:'UV examination'}[kind]});sound.scan();scene.scan(kind);tab='evidence';sync();render();}
function ask(kind){const result=question(state,kind);if(!result)return;lastReply=result;log.push({kind:'testimony',title:{alibi:'Account of whereabouts',memory:'A familiar memory',explain:'Explanation'}[kind],text:result});sound.speak(result);sync();render();}
function choice(action){
  if(!decide(state,action))return false;
  sound.hush();if(action!=='shoot'){sound.click();scene.leave(action);}else{sound.shot();const flash=document.querySelector('#flash');flash.classList.add('fired');setTimeout(()=>flash.classList.remove('fired'),180);}
  scene.unlock();sync();render();return true;
}
function shoot(hit){if(!state||state.phase!=='arrival'||modal)return false;if(state.ammo<=0){toast('Empty. Two more rounds arrive at the next watch.');return false;}if(!hit){state.ammo--;state.noise+=24;sound.shot();scene.recoil=1;scene.muzzleLight.intensity=100;scene.muzzleMesh.visible=true;toast('Missed. The shot echoes down the corridor.');sync();render();return false;}return choice('shoot');}
function continueGame(){const result=advance(state);if(result?.type==='ending'){screen='ending';scene.setMode('ending');sound.dread();intercom.disconnect().catch(()=>{});sync();render();}else if(result?.type==='interval'){scene.showPerson(null);sound.dread();sync();render();}else if(result)arrive();}
function look(target){const el=document.querySelector('#look-target');if(el)el.innerHTML=target?`<kbd>E</kbd> ${esc(target.name)}`:'';}
function interact(id){if(!state||screen!=='game')return;if(id==='door'){scene.focus('door');scene.unlock();render();return;}if(id==='records'){scene.focus('records');for(const k of ['protocol','register','incident'])if(!state.notes.includes(k))state.notes.push(k);sync();showModal('records');}if(id==='board'){scene.focus('board');if(!state.notes.includes('photograph'))state.notes.push('photograph');sync();showModal('photograph');}if(id==='radio'){scene.focus('radio');showModal('radio');}}
function showModal(name){scene.unlock();scene.keys={};modal=name;sound.click();render();requestAnimationFrame(()=>document.querySelector('.modal button, .modal input')?.focus());}
function closeModal(){modal=null;render();}
function render(){
  scene.paused=!!modal;
  app.innerHTML=screen==='menu'?menuHTML():screen==='ending'?endingHTML():gameHTML();
  if(modal){app.firstElementChild.inert=true;app.insertAdjacentHTML('beforeend',modalHTML());}
  if(screen==='game'){app.insertAdjacentHTML('beforeend',`<button id="voice-live" data-action="voice-stop" ${voiceState==='Disconnected'?'hidden':''}>${voiceState==='Microphone muted'?'MIC MUTED':'INTERCOM LIVE'} · DISCONNECT</button>`);}
}
function menuHTML(){const saved=loadGame();return `<main class="title-screen"><header class="title-header"><div class="school-mark">${icon('shield')}<span>BUKIT SENJA<br><b>NIGHT INSTITUTE</b></span></div><span class="edition">AN INTERACTIVE HORROR EXPERIENCE</span><button class="icon-button" data-action="settings" aria-label="Settings">${icon('gear')}</button></header><section class="title-content"><div class="eyebrow"><i class="status-dot"></i> SINGAPORE · 01°22′N 103°46′E</div><h1>LAST<br><span>BELL</span><i>.</i></h1><div class="title-rule"></div><p class="tagline">They look like people you know.<br>That’s how it starts.</p><div class="menu-actions"><button class="primary start-button" data-action="${saved?'resume':'new'}"><span>${saved?'CONTINUE THE NIGHT':'BEGIN THE NIGHT'}</span>${icon('arrow')}</button>${saved?'<button class="text-button" data-action="new">Start a new night</button>':''}<div class="menu-secondary"><button data-action="howto">How to survive</button><span>/</span><button data-action="settings">Settings</button></div></div></section><aside class="advisory"><span class="eyebrow">CAMPUS ADVISORY — 23:07</span><p>Remain in your classroom.<br>Do not open the door<br><em>unless you are certain.</em></p><span class="small muted">Transmission repeats every 60 seconds.</span><div class="waveform" aria-hidden="true">${Array.from({length:31},(_,i)=>`<i style="--h:${8+(Math.sin(i*2.3)+1)*14}px;--d:${i*.07}s"></i>`).join('')}</div></aside><footer class="title-footer"><span>${icon('sound')} HEADPHONES RECOMMENDED</span><span class="content-note">18+ · Fictional adult cast · Violence & psychological horror</span><span class="build-label">NIGHT SHIFT / 001</span></footer></main>`;}
function gameHTML(){
  const p=current(state),waiting=state.phase==='arrival';
  return `<main class="game-screen"><header class="hud"><div class="brand-mini">LAST BELL<span>BLOCK B / ROOM 04–07</span></div><div class="watch"><i class="status-dot"></i><span>WATCH 0${state.night}<small>${['23:00 — 01:00','01:00 — 03:00','03:00 — 06:00'][state.night-1]}</small></span><div class="watch-ticks">${[1,2,3].map(n=>`<i class="${n<=state.night?'lit':''}"></i>`).join('')}</div></div><div class="hud-actions"><button class="icon-button" data-action="notebook" aria-label="Open notebook">${icon('book')}</button><button class="icon-button" data-action="radio" aria-label="Open intercom">${icon('radio')}</button><button class="icon-button" data-action="pause" aria-label="Pause game">${icon('gear')}</button></div></header>
  ${state.phase==='interval'?intervalHTML():`<div class="encounter-layout"><section class="identity panel"><div class="panel-overline"><span>${waiting?'SOMEONE AT THE DOOR':'DECISION RECORDED'}</span><span>${String(state.index+1).padStart(2,'0')} / 12</span></div><h2>${esc(p?.name||'')}</h2><p class="role">${esc(p?.role||'')} <span>· ${p?.age||''}</span></p><div class="identity-line"><i class="status-dot amber"></i> IDENTITY UNVERIFIED</div><blockquote>“${esc(lastReply||p?.opening||'')}”</blockquote>${waiting?`<div class="question-list"><span class="eyebrow">ASK THEM</span>${[['alibi','Where were you?'],['memory','Tell me something about the school.'],['explain','Explain what I am seeing.']].map(([key,label])=>`<button data-ask="${key}" ${p.asked.includes(key)?'disabled':''}>${label}<span>${p.asked.includes(key)?'✓':'↗'}</span></button>`).join('')}</div>`:`<p class="aftermath-text">${p?.decision==='admit'?'The lock opens. They step inside. From behind you, someone whispers, “Are you sure?”':p?.decision==='reject'?'Their footsteps fade into the rain. You wait for a scream. None comes. Somehow that is worse.':'The report cracks through the classroom. They fall. The corridor is quiet for a moment. Then something knocks, far away.'}</p><button class="primary wide" data-action="continue">${state.index%4===3?'END THIS WATCH':'WAIT FOR THE NEXT KNOCK'}${icon('arrow')}</button>`}</section>
  <aside class="dossier panel"><div class="panel-overline"><span>${icon('book')} FIELD NOTES</span><span>${log.length.toString().padStart(2,'0')}</span></div><div class="tabs" role="tablist" aria-label="Dossier sections">${[['evidence','Evidence'],['record','Record'],['shelter','Shelter']].map(([key,label])=>`<button role="tab" aria-selected="${tab===key}" class="${tab===key?'active':''}" data-tab="${key}">${label}</button>`).join('')}</div><div class="dossier-body" role="tabpanel">${dossierHTML(p)}</div><div class="dossier-foot">A sign is a clue. Never a verdict.</div></aside></div>
  <div class="crosshair" aria-hidden="true"><i></i><i></i></div><div id="look-target" class="look-target"></div>
  ${waiting?`<div class="decision-bar"><div class="tools"><span class="eyebrow">EXAMINE <small>−7 SEC</small></span><div>${[['thermal','thermal','Temperature','1'],['pulse','pulse','Pulse','2'],['uv','uv','UV light','3']].map(([key,ic,label,num])=>`<button data-scan="${key}" ${p.scans.includes(key)?'disabled':''}>${icon(ic)}<span>${label}</span><kbd>${p.scans.includes(key)?'✓':num}</kbd></button>`).join('')}</div></div><div class="decisions"><button class="admit" data-choice="admit">${icon('door')} LET INSIDE</button><button data-choice="reject">TURN AWAY</button><button class="shoot" data-action="shoot" ${state.ammo<=0?'disabled':''}>${icon('target')} SHOOT</button></div><div class="timer"><span id="countdown">${Math.ceil(state.time)}</span><small>SECONDS<br>TO DECIDE</small></div></div>`:''}`}
  <footer class="game-footer"><div class="meters"><span>${icon('shield')}<b>${state.health}</b><small>RESOLVE</small></span><span>${icon('pulse')}<b>${state.trust}%</b><small>TRUST</small></span><span>${icon('bullet')}<b>${String(state.ammo).padStart(2,'0')}</b><small>ROUNDS</small></span><span class="noise-meter"><i style="width:${Math.min(100,state.noise)}%"></i><small>NOISE ${Math.round(state.noise)}</small></span></div><div class="room-links"><button data-place="records">Records</button><button data-place="board">Noticeboard</button><button data-place="door">Door</button></div><div class="control-hint"><kbd>WASD</kbd> move <kbd>E</kbd> interact <kbd>ESC</kbd> pause</div></footer></main>`;
}
function dossierHTML(p){
  if(tab==='record')return `<span class="eyebrow">OFFICIAL CAMPUS RECORD</span><p>${esc(p?.record||'No record available.')}</p><div class="note-caution">A copied identity will match the register. Compare the account with what you observe.</div>`;
  if(tab==='shelter')return state.sheltered.length?`<span class="eyebrow">INSIDE THE CLASSROOM</span>${state.sheltered.map(id=>{const p=PEOPLE.find(p=>p.id===id);return `<div class="shelter-person">${icon('shield')}<span>${p.name}<small>${p.role}</small></span><i class="status-dot"></i></div>`;}).join('')}`:'<div class="empty-note"><span>00</span><p>Only you, for now.</p><small>Anyone you admit stays for the night.</small></div>';
  return log.length?log.map(item=>`<article class="evidence ${item.anomaly?'anomaly':''}"><div>${icon(item.kind==='testimony'?'book':item.kind)}<h3>${esc(item.title)}</h3>${item.anomaly?'<span class="tiny-tag">UNUSUAL</span>':''}</div><p>${esc(item.text)}</p></article>`).join(''):'<div class="empty-note">'+icon('target')+'<p>You have only their word.</p><small>Examine the person at the door.<br>Compare their answers with the record.</small></div>';
}
function intervalHTML(){return `<section class="watch-card panel"><span class="eyebrow">THE SCHOOL SETTLES. SOMETHING ELSE DOES NOT.</span><h2>0${state.night}:00</h2><p>${state.health<85?'You wake to a chair scraping against the floor. Someone has moved closer. Your resolve is slipping.':'The lights dim. Rain taps against the corridor. Somewhere below, a door closes very gently.'}</p><div class="watch-summary"><span>${state.sheltered.length}<small>INSIDE</small></span><span>${state.health}<small>RESOLVE</small></span><span>+2<small>ROUNDS FOUND</small></span></div><button class="primary wide" data-action="nextwatch">BEGIN WATCH 0${state.night}${icon('arrow')}</button><button class="text-button" data-action="notebook">Review your notebook</button></section>`;}
function endingHTML(){const end=ENDINGS[state.ending];const saved=state.decisions.filter(d=>d.action==='admit'&&!d.visitor).length;return `<main class="ending-screen"><span class="eyebrow">06:00 / AFTER-ACTION REPORT / SEED ${state.seed}</span><h1>${end.title}</h1><p class="ending-subtitle">${end.subtitle}</p><p>${end.text}</p><div class="ending-stats"><span>${saved}<small>HUMANS SHELTERED</small></span><span>${state.decisions.filter(d=>d.action==='shoot'&&!d.visitor).length}<small>INNOCENT LIVES TAKEN</small></span><span>${state.notes.length}<small>DOCUMENTS RECOVERED</small></span></div><details class="ledger"><summary>See who was really at the door</summary>${state.decisions.map(d=>`<div><span>${PEOPLE.find(p=>p.id===d.id).name}</span><b class="${d.visitor?'red':''}">${d.visitor?'VISITOR':'HUMAN'}</b><small>${d.action==='admit'?'Sheltered':d.action==='reject'?'Turned away':'Shot'}</small></div>`).join('')}</details><div class="ending-actions"><button class="primary" data-action="new">ANOTHER NIGHT ${icon('arrow')}</button><button data-action="menu">Main menu</button></div><span class="small muted">${Object.keys(ENDINGS).indexOf(state.ending)+1} / 6 ENDINGS · Every new night changes who you can trust.</span></main>`;}
function documentHTML(key){const d=DOCUMENTS[key];return `<article class="document"><span class="eyebrow">${d.tag}</span><h3>${d.title}</h3>${d.text.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</article>`;}
function modalHTML(){let title='',body='';
  if(modal==='settings'||modal==='pause'){title=modal==='pause'?'The night can wait.':'Settings';body=`<div class="setting"><label for="volume">Sound volume</label><input id="volume" type="range" min="0" max="1" step="0.05" value="${settings.volume}" /></div>${[['blood','Blood effects','Blood spray and impact pools.'],['motion','Camera movement','Head bob and idle weapon sway.'],['voices','Read dialogue aloud','Uses voices installed in your browser.']].map(([key,label,desc])=>`<label class="setting toggle"><span>${label}<small>${desc}</small></span><input type="checkbox" data-setting="${key}" ${settings[key]?'checked':''}/></label>`).join('')}<div class="modal-actions"><button class="primary" data-action="close">${screen==='game'?'RESUME':'DONE'}${icon('arrow')}</button>${screen==='game'?'<button data-action="menu">Save & main menu</button>':''}</div>`;}
  if(modal==='briefing'||modal==='howto'){title='Keep the door.';body=`<span class="eyebrow">BUKIT SENJA NIGHT INSTITUTE · ADULT EDUCATION</span><p>You are the night security officer. The campus is sealed. Twelve teachers and adult students will ask for shelter over three watches. Some are no longer human.</p><div class="instructions"><div><b>01</b><p><strong>Listen. Examine. Compare.</strong>Use temperature, pulse and UV scans. Check their account against the record. Every test consumes time; no single clue is certain.</p></div><div><b>02</b><p><strong>Make the call.</strong>Admit them, send them away, or shoot. Visitors inside drain your resolve. Gunfire attracts danger. Killing innocent people changes your ending.</p></div><div><b>03</b><p><strong>Search the classroom.</strong>The cabinet, noticeboard and radio hold another way out. Survive until 06:00. Your progress saves on this device.</p></div></div><div class="key-grid"><span><kbd>W A S D</kbd> Move</span><span><kbd>CLICK SCENE</kbd> Mouse look</span><span><kbd>RMB + LMB</kbd> Aim + fire</span><span><kbd>1 / 2 / 3</kbd> Examine</span><span><kbd>E</kbd> Interact</span><span><kbd>ESC</kbd> Pause / cursor</span></div><p class="small muted">Mouse-look is optional. All decisions, examinations and room locations are also available as on-screen buttons. Contains graphic violence, sudden sounds and dread. All characters are fictional adults.</p><button class="primary wide" data-action="close">${modal==='briefing'?'TAKE YOUR POST':'UNDERSTOOD'}${icon('arrow')}</button>`;}
  if(modal==='records'){title='Records cabinet';body=documentHTML('incident')+documentHTML('register')+documentHTML('protocol');}
  if(modal==='photograph'){title='Behind the noticeboard';body=documentHTML('photograph');}
  if(modal==='notebook'){title='Your notebook';body=state?.notes.length?state.notes.map(documentHTML).join(''):'<p>No documents recovered yet. Search the records cabinet and the noticeboard.</p>';}
  if(modal==='radio'){title='A voice on the wire.';body=`<span class="eyebrow">EMERGENCY INTERCOM / CHANNEL 04</span><p class="radio-quote">“If you can hear me, you are not alone in that room.”</p><div class="radio-terminal"><span class="eyebrow">${state?.signalOff?'CARRIER DISCONNECTED':'BASEMENT RELAY — MANUAL OVERRIDE'}</span>${state?.signalOff?'<p>The loudspeaker is silent. The relay is no longer calling them.</p>':'<p>A four-digit override. Someone left a reminder in the school records.</p><form id="override"><label class="sr-only" for="code">Four-digit relay override</label><input id="code" name="code" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" placeholder="— — — —" required autocomplete="off"/><button type="submit">DISCONNECT RELAY</button></form><p id="override-result" role="status"></p>'}</div><div class="voice-section"><div class="panel-overline"><span>${icon('radio')} LIVE VOICE INTERCOM</span><span id="voice-state">${esc(voiceState)}</span></div><p class="small">Speak to the school intercom through ElevenLabs. Connecting sends microphone audio and your current in-game observations to ElevenLabs. Voice chat is optional and cannot make game decisions for you.</p>${!agentId?'<label class="field-label" for="agent-id">ElevenLabs public agent ID</label><input id="agent-id" placeholder="agent_…" autocomplete="off"/><p class="small muted">No agent connected yet. Use a public agent configured for this game. Never enter an API key.</p>':''}<div class="voice-buttons"><button class="primary" data-action="voice-connect">CONNECT MICROPHONE</button><button data-action="voice-mute">MUTE / UNMUTE</button><button data-action="voice-stop">DISCONNECT</button></div><div id="transcript" class="transcript" aria-live="polite">${transcript.map(t=>`<p><b>${esc(t.who)}</b>${esc(t.text)}</p>`).join('')}</div></div>`;}
  return `<div class="modal-backdrop"><section class="modal ${modal==='briefing'||modal==='howto'?'wide-modal':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></header><div class="modal-body">${body}</div><span class="modal-footer">${screen==='game'?'THE NIGHT IS PAUSED':'LAST BELL / PLAYER SETTINGS'}</span></section></div>`;
}
app.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.scan)return performScan(b.dataset.scan);
  if(b.dataset.ask)return ask(b.dataset.ask);
  if(b.dataset.choice)return choice(b.dataset.choice);
  if(b.dataset.tab){tab=b.dataset.tab;render();return;}
  if(b.dataset.place)return interact(b.dataset.place);
  const a=b.dataset.action;
  if(a==='new'){start();return;}if(a==='resume'){start(true);return;}
  if(['settings','pause','howto','notebook','radio'].includes(a)){showModal(a);return;}
  if(a==='close'){closeModal();return;}if(a==='menu'){sync();menu();return;}
  if(a==='continue'){continueGame();return;}if(a==='nextwatch'){nextWatch(state);arrive();return;}
  if(a==='shoot'){scene.focus('door');scene.fire(true);return;}
  if(a==='voice-connect'){
    if(state?.signalOff){toast('The relay is disconnected. The intercom is silent.');return;}
    const entered=document.querySelector('#agent-id')?.value.trim();if(entered)agentId=entered;
    sound.hush();try{await intercom.connect(agentId,context());}catch(error){toast(error.name==='NotAllowedError'?'Microphone access was declined. You can still play normally.':error.message||'Unable to connect. Check the agent configuration.');}return;
  }
  if(a==='voice-mute')intercom.mute();if(a==='voice-stop')await intercom.disconnect();
});
app.addEventListener('input',e=>{if(e.target.id==='volume'){settings.volume=Number(e.target.value);sound.setVolume(settings.volume);}if(e.target.dataset.setting){settings[e.target.dataset.setting]=e.target.checked;scene.blood=settings.blood;scene.motion=settings.motion;sound.voices=settings.voices;if(!settings.voices)sound.hush();}try{localStorage.setItem('last-bell-settings',JSON.stringify(settings));}catch{}});
app.addEventListener('submit',e=>{if(e.target.id!=='override')return;e.preventDefault();const result=unlockSignal(state,new FormData(e.target).get('code'));sound.scan();sync();if(result.ok){intercom.disconnect().catch(()=>{});render();toast(result.text);}else document.querySelector('#override-result').textContent=result.text;});
document.addEventListener('keydown',e=>{
  if(e.key==='Tab'&&modal){const focusables=[...document.querySelectorAll('.modal button:not(:disabled),.modal input')];const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}
  if(e.target.matches('input,textarea'))return;
  if(e.code==='Escape'){e.preventDefault();if(modal)closeModal();else if(screen==='game')showModal('pause');return;}
  if(modal||screen!=='game'||e.repeat)return;
  if(['Digit1','Digit2','Digit3'].includes(e.code))performScan({Digit1:'thermal',Digit2:'pulse',Digit3:'uv'}[e.code]);
  if(e.code==='KeyE'&&scene.lookTarget)interact(scene.lookTarget.id);
});
// Hidden tabs and dialogs pause the deadline; decisions and scans autosave immediately.
setInterval(()=>{if(screen!=='game'||modal||document.hidden||state.phase!=='arrival')return;state.time=Math.max(0,state.time-1);const el=document.querySelector('#countdown');if(el){el.textContent=Math.ceil(state.time);el.classList.toggle('urgent',state.time<20);}if(state.time===20){sound.knock();toast('They will not wait much longer.');}if(state.time<=0){choice('reject');toast('You waited too long. They have left.');}if(state.time%5===0)saveGame(state);},1000);
document.addEventListener('visibilitychange',()=>{scene.keys={};if(document.hidden){sound.hush();if(intercom.session&&!intercom.muted)intercom.mute();}});
window.addEventListener('beforeunload',()=>{if(state)saveGame(state);intercom.disconnect().catch(()=>{});});
render();
