import {upload} from '@vercel/blob/client';
import {AUDIO_ACCEPT,audioExtension,audioContentType} from './audio-formats.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountMusicLibrary(host,{authenticated=false}={}){
 let tracks=[],busy=false;
 host.innerHTML=`<div class="music-heading"><div><p class="eyebrow">The turntable</p><h2>Music for the house.</h2><p>Interact with the record player to play or stop. Tracks play one after another, then repeat.</p></div><button type="button" data-music="refresh">Refresh music</button></div><p class="music-status" role="status"></p>${authenticated?`<form class="music-upload" data-music-drop><label>Drop audio files here or choose files<input type="file" name="tracks" multiple accept="${AUDIO_ACCEPT}" required></label><p class="fine">MP3, M4A/AAC, WAV, Ogg/Opus, FLAC or WebM audio. Up to 100 MB per file. Uploaded tracks are enabled for visitors to the game; you can turn individual tracks off below.</p><button class="primary">Upload music</button><progress max="100" value="0" hidden></progress></form>`:'<p>Sign in above to upload audio files and manage the music library.</p>'}<div class="music-tracks"></div>`;
 const status=text=>{if(host.isConnected)host.querySelector('.music-status').textContent=text;};
 const lock=value=>{busy=value;host.querySelectorAll('input,button').forEach(el=>el.disabled=value);};
 async function api(query='',body){const r=await fetch('/api/music'+query,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{}),credentials:'same-origin'});let data;try{data=await r.json();}catch{throw Error('Open this editor on the live site to manage cloud music.');}if(!r.ok)throw Error(data.error||'Could not load music');return data;}
 async function refresh(){tracks=await api(authenticated?'?admin=1':'');if(!host.isConnected)return;host.querySelector('.music-tracks').innerHTML=tracks.map(t=>`<form data-track="${t.id}"><label>Track title<input name="title" maxlength="100" required value="${esc(t.title)}" ${authenticated?'':'readonly'}></label>${t.deleting?'<p>Deletion incomplete. Retry Delete track to finish.</p>':`<audio controls preload="none" src="${esc(t.src)}"></audio>`}${authenticated?`<label class="check"><input type="checkbox" name="enabled" ${t.enabled?'checked':''}><span>Play this track in the house</span></label><div class="row"><button ${t.deleting?'disabled':''}>Save track</button><button type="button" class="danger-text" data-music="delete" data-id="${t.id}">Delete track</button></div>`:''}</form>`).join('')||'<p class="fine">No uploaded music yet. The turntable plays a gentle house melody until you add your music.</p>';}
 async function uploadFiles(input){
  const files=Array.from(input);if(!files.length||files.length>30)throw Error('Choose between 1 and 30 audio files');
  if(files.some(f=>!audioContentType(f.name)||f.size===0||f.size>100*1024*1024))throw Error('Choose supported audio files of up to 100 MB each');
  lock(true);let completed=0;try{const progress=host.querySelector('progress');progress.hidden=false;
   for(const file of files){const id=crypto.randomUUID(),path=`music/${id}.${audioExtension(file.name)}`;status(`Uploading ${completed+1} of ${files.length}: ${file.name}`);
    await upload(path,file,{access:'private',handleUploadUrl:'/api/music-upload',multipart:true,contentType:audioContentType(file.name),onUploadProgress:({percentage})=>progress.value=(completed+percentage/100)/files.length*100});
    await api('',{id,path,title:file.name.replace(/\.[^.]+$/,'').slice(0,100)||'Untitled track',enabled:true});completed++;
   }host.querySelector('input[type=file]').value='';status(`${completed} track${completed===1?'':'s'} added. They are ready on the turntable.`);await refresh();
  }catch(error){status(`${completed?`${completed} tracks saved. `:''}${error.message}`);await refresh().catch(()=>{});}finally{lock(false);}
 }
 host.addEventListener('submit',async e=>{e.preventDefault();e.stopPropagation();if(busy)return;try{if(e.target.classList.contains('music-upload')){await uploadFiles(e.target.querySelector('input').files);return;}const track=tracks.find(t=>t.id===e.target.dataset.track),f=new FormData(e.target);lock(true);await api('',{...track,title:f.get('title'),enabled:f.has('enabled')});status('Track saved.');await refresh();}catch(error){status(error.message);}finally{lock(false);}});
 host.addEventListener('click',async e=>{const b=e.target.closest('[data-music]');if(!b||busy)return;try{if(b.dataset.music==='delete'){const t=tracks.find(t=>t.id===b.dataset.id);const confirmed=await new Promise(resolve=>{const d=document.createElement('dialog');d.className='delete-dialog';d.innerHTML=`<h2>Delete this track?</h2><p>${esc(t.title)}</p><p>This removes the uploaded audio file from the turntable library.</p><form method="dialog"><button value="cancel" autofocus>Keep track</button><button value="delete" class="danger">Delete track</button></form>`;d.addEventListener('close',()=>{resolve(d.returnValue==='delete');d.remove();},{once:true});document.body.append(d);d.showModal();});if(!confirmed)return;lock(true);await api('?action=delete',{id:t.id,etag:t.etag});status('Track deleted.');}lock(true);await refresh();}catch(error){status(error.message);}finally{lock(false);}});
 host.addEventListener('dragover',e=>{if(e.target.closest('[data-music-drop]')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
 host.addEventListener('drop',async e=>{if(!e.target.closest('[data-music-drop]'))return;e.preventDefault();if(busy)return;try{await uploadFiles(e.dataTransfer.files);}catch(error){status(error.message);}});
 refresh().catch(error=>status(error.message));
}
